// Generated by Atlas! Do not edit manually!
export type { CContract as CClientConfig } from "./assets/client-config.contract";
export { Contract as ClientConfig } from "./assets/client-config.contract";
