// Generated by Atlas! Do not edit manually!
export enum ApiQueryParams {
  ProjectId = "appId",
  RedirectUri = "redirectUri",
}

export enum ApiPathParams {
  ProjectId = "projectId",
}

export enum ApiHeaders {
  ApiVersion = "akc-api-version",
}

/**
 * API Versions for Api Servers.
 * These versions can be used to prevent errors during contract changes.
 * Allocate new versions here and adhere to the structure defined below:
 * @example
 * export enum ApiVersion {
     v2025_06_01 = "2025-06-01", // Main Version used for general updates
     v2025_06_01_01 = "2025-06-01.01", // Patch Version used for hot fixes
   }
 */
export enum ApiVersions {
  v2025_06_01 = "2025-06-01",
  v2026_01_01 = "2026-01-01",
}
