// Generated by Atlas! Do not edit manually!
import {
  Policy,
  ResourcePolicy,
  ResourcePolicyComputeType,
  resourcePolicyList,
  resourcePolicyLiterals,
  resourcePolicyMap,
  ResourcePolicyString,
  ResourcePolicyType,
} from "@atlas/scaffold/ResourcePolicy";

export enum IAMResource {
  IAM_Root = "iam-root", // IAM Root
  IAM_OrgAdmin = "iam-org-admin", // IAM Org Admin
  IAM_TeamAdmin = "iam-team-admin", // IAM Team Admin
}

export enum OrgResource {
  OrgVerification = "org-verification", // Verify Organizations
  OrgSettings = "org-settings", // Organization Level Settings
}

export enum TeamAdminResource {
  TeamMember = "team-member",
}

type ResourceEnums<T extends Record<string, string>> = T[keyof T];
export const Resource = {
  ...IAMResource,
  ...OrgResource,
  ...TeamAdminResource,
};
export type Resource = ResourceEnums<typeof Resource>;

export const AtlasPolicy = ResourcePolicy<Resource>;
export const AtlasPolicyLiterals = resourcePolicyLiterals(Resource);
export const AtlasPolicyMap = resourcePolicyMap(Resource);
export const AtlasPolicyList = resourcePolicyList(Resource);
export declare type AtlasPolicy = ResourcePolicy<Resource>;
export declare type AtlasPolicyType = ResourcePolicyType<Resource>;
export declare type AtlasPolicyComputeType = ResourcePolicyComputeType<Resource>;
export declare type AtlasPolicyString = ResourcePolicyString<Resource>;
